### ISSUE TITLE
Forced relogin upon container restart

### ISSUE THREAD

**Issue by immanuelfodor** [shaarli/Shaarli#1673]
I started running Shaarli in Kubernetes (k8s) this afternoon, and observed a strange behavior that was not present with docker-compose previously.

Shaarli is a `Deployment` with replicas=1, so the container is running within a `Pod` with persistent storage attached to the `cache` and `data` folders. When the Pod is deleted (a regular thing to do a restart of an app), k8s schedules another Pod based on the template of the Deployment. The new pod receives a new random hostname and a new IP within the k8s cluster. Examples: 
- before: `shaarli-58f4db94b4-gqlx5` and `10.42.1.4`
- after: `shaarli-58f4db94b4-z7vcq` and `10.42.1.218`

After such a restart, Shaarli forces a login even though I was logged in previously. My force_login option is turned on by the way in the config to restrict public access. I suspect something is related to the hostname change, as docker-compose restart never did such thing (as far as I remember). Is something with the login cookie tied to the hostname? 

Additional context: 

I must add, my last Shaarli build was about a month or two ago, so there can be any code related change in the meantime that would cause the same effect with docker-compose as well. It's just too suspicious that with compose running in a VM, the hostname and IP never changed. 

Also, here is my login logs:

```bash
$ cat data/log.txt
[2020-12-31 19:33:33.594033] [info] - 192.168.1.101_192.168.1.11 - Login successful
[2020-12-31 20:25:01.353993] [info] - 192.168.1.103_192.168.1.11 - Login successful
```

Maybe the IPs are related, too:
- The first IP is the particular k8s node Shaarli was running on, the second IP is the client with the browser. Before the Docker image was rebuilt, the log contained only one IP, the client's. 
- Shaarli's Docker container log now always contains the node IP. 

The k8s ingress controller surely passes the client IP to the container it received the request from (`use-forwarded-headers: "true"`), and the external load balancer passes the following related headers to the ingress controller: 

```
proxy_set_header  Host              $host;
proxy_set_header  X-Real-IP         $remote_addr;
proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header  X-Forwarded-Proto $scheme;
proxy_set_header  X-Forwarded-Host  $host;
```

I understand you might not have experience with Kubernetes but you surely know Shaarli's auth and cookie mechanisms better than me, you probably can think of somehting that can cause the forced relogin in this case.

**Comment by ArthurHoaro** [comment]
There are multiple things at work here, and I'm not sure which one is at fault, so I'll try to explain it and let you run a few tests.

  - PHP sessions are by default stored in the filesystem - I believe in `/tmp` - which won't be shared between pods here.
  - Cookies are attached to a specific domain. So I'm not sure what you mean by « The new pod receives a new random hostname ». Is that behind the reverse proxy or the hostname you use to access Shaarli? You can check cookies domain in the browser debugger.
  - client IP is determined [here](https://github.com/shaarli/Shaarli/blob/master/application/http/HttpUtils.php#L461), which contains a helpful comment
  - Because your generated IP token is changing, you should check *Disable session cookie hijacking protection* in your setting page and retest it.

**Comment by ArthurHoaro** [comment]
Also playing with Shaarli and k8s is on my todo list, but I couldn't find the time to do so yet. So if you have resources to share, a helm chart or anything, feel free to do so :)

**Comment by immanuelfodor** [comment]
Ohhh, so the /tmp folder is indeed recreated with every new pod, that must be it! Tmp is not on persistent storage, yes. 

> The new pod receives a new random hostname

When you exec into the pod, its hostname is that randomized pod name. The external domain (shaarli.example.com) doesn't change, just the pod's internal hostname. But then it's not related to the cookie. 

Thnaks for the IP code link, this shed the light on why is there an underscore in the logs. The remote IP must be the node IP where the ingress controller received the request from the external load balancer (reverse proxy), so it adds the ingress IP as remote IP, and passes down the X forwarded header coming from the reverse proxy, that is the original client IP in the second part. Working as intended then, thank you. 

Enabled the "Disable session cookie hijacking protection" (was turned off originally), then killed the pod, it got restarted, and Shaarli logged me out. I think this also verifies the tmp folder theory, as it gets deleted, all sessions cease to exist. 

Here is my Shaarli k8s YAML config. I'm using the `nfs-client-provisioner` project for easy volume provisioning, and `cert-manager` for generating a self-signed cert that secures the inter-VLAN communication to the reverse proxy that holds the valid external SSL cert. However, I don't know if NFS will be suitable on the long run based on #953 😀 I also use `keel` to update the image from my Drone CI with a webhook call upon I rebuild and push my own Dockerfile (#1372). The image pull secret is a Docker config JSON according to k8s docs providing login to the Docker registry.

```yaml
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shaarli-data
  labels:
    name: shaarli
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "200Mi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaarli
  labels:
    app: shaarli
  annotations:
    keel.sh/approvals: "0"
    keel.sh/policy: force
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/trigger: poll
    keel.sh/releaseNotes: "https://github.com/shaarli/Shaarli https://github.com/kalvn/Shaarli-Material"
spec:
  selector:
    matchLabels:
      app: shaarli
  template:
    metadata:
      labels:
        app: shaarli
    spec:
      containers:
        - name: shaarli
          image: "my.docker.registry/shaarli/shaarli:master"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              subPath: data
              mountPath: /var/www/shaarli/data
            - name: data
              subPath: cache
              mountPath: /var/www/shaarli/cache
          resources:
            limits:
              cpu: 300m
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 200Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shaarli-data
      imagePullSecrets:
        - name: shaarli-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: shaarli
  labels:
    app: shaarli
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: shaarli
  sessionAffinity: None

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: shaarli-selfsigned
  labels:
    app: shaarli
spec:
  selfSigned: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shaarli
  annotations:
    cert-manager.io/issuer: "shaarli-selfsigned"
  labels:
    app: shaarli
spec:
  rules:
    - host: shaarli.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shaarli
                port:
                  name: http
  tls:
    - hosts:
        - shaarli.example.com
      secretName: shaarli-cert
```

A `NetworkPolicy` config and a container security context for the Deployment would be a nice addition in the future.
