### ISSUE TITLE
Config file '/usr/src/app/shaarli/mkdocs.yml' does not exist.

### ISSUE THREAD

**Issue by Djeremaille** [shaarli/Shaarli#1755]
Hi!
I'm trying to build a docker armhf image  on a Raspberry pi 4 (ubuntu 20.04 arm64) but I have this error:
```
Installing collected packages: MarkupSafe, Jinja2, Markdown, click, futures, six, singledispatch, backports-abc, tornado, livereload, PyYAML, mkdocs
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Running setup.py install for tornado: started
    Running setup.py install for tornado: finished with status 'done'
  Running setup.py install for livereload: started
    Running setup.py install for livereload: finished with status 'done'
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
Successfully installed Jinja2-2.11.3 Markdown-3.1.1 MarkupSafe-1.1.1 PyYAML-5.4.1 backports-abc-0.5 click-7.1.2 futures-3.3.0 livereload-2.6.3 mkdocs-1.0.4 singledispatch-3.6.1 six-1.16.0 tornado-5.1.1

Config file '/usr/src/app/shaarli/mkdocs.yml' does not exist.
ERROR: Service 'shaarli' failed to build : The command '/bin/sh -c apk --update --no-cache add py2-pip     && cd /usr/src/app/shaarli     && pip install --no-cache-dir mkdocs     && mkdocs build --clean' returned a non-zero code: 1

```
I downloaded the Dockerfilearmhf and renamed it Dockerfile. 
I also changed the docker-compose.yml to use my Traefik instance:
```
---
# Shaarli - Docker Compose example configuration
#
# See:
# - https://shaarli.readthedocs.io/en/master/Docker/#docker-compose
#
# Environment variables:
# - SHAARLI_VIRTUAL_HOST      Fully Qualified Domain Name for the Shaarli instance
# - SHAARLI_LETSENCRYPT_EMAIL Contact email for certificate renewal
# - SHAARLI_DOCKER_TAG        Shaarli docker tag to use
#                             See: https://hub.docker.com/r/shaarli/shaarli/tags
version: '3'
networks:
  traefik:
    external:
      name: traefik
  default:



volumes:
  shaarli-cache:
  shaarli-data:

services:
  shaarli:
    image: shaarli/shaarli:${SHAARLI_DOCKER_TAG}
    build: ./
    networks:
      - traefik
      - default
    volumes:
      - shaarli-cache:/var/www/shaarli/cache
      - shaarli-data:/var/www/shaarli/data
    ports:
      - 88:80
      - 448:443
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.shaarli.entrypoints=web"
      - "traefik.http.routers.shaarli.rule=Host(`shaarli.example.org`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.shaarli.middlewares=https-redirect"

      - "traefik.http.routers.shaarli-secure.entrypoints=websecure"
      - "traefik.http.routers.shaarli-secure.rule=Host(`shaarli.example.org`)"
      - "traefik.http.routers.shaarli-secure.tls=true"
      - "traefik.http.routers.shaarli-secure.tls.certresolver=myresolver"


```
And here is my .env:
```
SHAARLI_VIRTUAL_HOST=shaarli.example.com
SHAARLI_LETSENCRYPT_EMAIL=example@mail.com
SHAARLI_DOCKER_TAG=armhf

```

Can someone help me to solve this?
