### ISSUE TITLE
Feature request: Dark theme

### ISSUE THREAD

**Issue by Albirew** [shaarli/Shaarli#1811]
I tried to make a dark edition of default theme (almost only focused on main page for visitors but it doesn't break anything on other pages so it's fine as is imo) using `data/user.css`
You can use it as a "base" for something better:
```css
:root{
  --background-color:#333;
}
.linklist-item{
  background:#333;
}
.linklist-item-title,
.linklist-item-infos{
  background: #222;
}
.linklist-item-infos a:hover{
  color: #fff;
}
.linklist-item-infos a,
.linklist-item-description,
.page-error-container,
.linklist-pages,
.fa-arrow-circle-right,
.footer-container,
.linksperpage,
.linklist-filters,
.footer-container a{
  color: #ddd;
}
.linkqrcode {
  filter: hue-rotate(180deg) invert(1);
}
.linklist-filters .filter-off {
  background: #222;
  color: #eee;
}
.page-form code,
.searchform-block input[type="text"],
.linksperpage input[type="text"],
.linksperpage a{
  background: #111;
  color: #ddd;
}
.edit-link{
color: #6c9ec9;
}
.markdown blockquote{
  color: #999;
  border-left: .5em #111 solid;
}
.markdown :not(pre) code {color: #444;}
```

You can see live result over there: https://liens.albirew.fr/
edit 2025-01-01: updated for 0.14
