### ISSUE TITLE
check for shaarli dead links

### ISSUE THREAD

**Issue by lmjst** [shaarli/Shaarli#1816]
Hi,
I'm looking for a dead link checker (within my shaarli inwtall).
I found https://framagit.org/qwertygc/shaarli-dev-code/-/blob/master/self-dead-link.php
but can't see how to use it ??
I've copied the file in my shaarli directory but the result is :
```
(0) S
(0) 
(0) 
(0) 
(0) 
(0) 
0.095519 secondsDone
```
Thanks

**Comment by nodiscc** [comment]
https://github.com/nodiscc/hecat/ is able to check for dead links in shaarli data. Check the [examples section for Shaarli](https://github.com/nodiscc/hecat/#shaarli) - here is a basic example that just check for dead links:


```bash
python3 -m venv .venv && source .venv/bin/activate && pip3 install shaarli-client
mkdir -p ~/.config/shaarli/ && nano ~/.config/shaarli/client.ini
```
```ini
# ~/.config/shaarli/client.ini
[shaarli]
url = https://links.example.org
secret = AAAbbbZZZvvvSSStttUUUvvVXYZ
```
```bash
shaarli --outfile /path/to/shaarli-export.json get-links --limit=all
nano .hecat.yml
```
```yaml
# .hecat.yml
steps:
  - name: import data from shaarli API JSON
      module: importers/shaarli_api
      module_options:
        source_file: /path/to/shaarli-export.json
        output_file: shaarli.yml

  - name: check URLs
    module: processors/url_check
    module_options:
      source_files:
        - shaarli.yml
```
```bash
source .venv/bin/activate && hecat -c .hecat.yml
```
