### ISSUE TITLE
Build front-end dependencies locally

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#755]
This is a follow-up to #754.

@nodiscc wrote:

> Is it possible/recommended to fetch 3rd-party eot,css,js... files during the build process? (as opposed to storing them in the git repository)

@ArthurHoaro wrote:

> Yes. We could use bower (dependency manager, kind of like composer, for front end libs) and include these in our release archives.

I have a mixed opinion regarding [Bower](https://bower.io/):
- it works fine and fills the role of a dependency manager, yet...
- Node stuff is a [PITA](https://2.bp.blogspot.com/-XZaq81q8ITw/VAm98VtJAFI/AAAAAAAAArk/PNVdnOxS7cI/s1600/Pain%2Bin%2BAss.jpg) to install _in a safe way_ on a server, as one is expected to _blindly_ use the [NodeSource repositories](https://nodejs.org/en/download/package-manager/):

```bash
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Nice, ain't it? `curl | sudo`... When the shell script merely adds the appropriate new APT entry and PGP key.

I wrote an Ansible task a while back to automate this for Debian-based systems:

```yaml
---
- name: Add APT key for NodeSource repositories
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource 6.x repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main' 
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Set NODE_PATH under /etc/environment
  lineinfile:
    dest: /etc/environment
    regexp: '^NODE_PATH'
    line: 'NODE_PATH="/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/local/lib/npm/lib/node_modules"'

- name: Install Bower and Gulp globally
  npm: name={{ item }} global=yes state=present
  with_items:
    - bower
    - gulp
```

This would be easy to add to Docker images and Shaarli Wiki, but I fear users will have a hard time to get it working, whether they install Node on a global- or user-scope.
